name: release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true

      - name: Build binaries
        run: bash -ex ./build/build.sh all

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*
          generate_release_notes: true
