name: release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
          cache: true

      - name: Build static binaries
        run: bash -ex .github/build.sh all

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: virt-launcher-*
